"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Session } from "../../lib/store";
import masterData from "../../lib/master-data.json";

const BRANCHES = ["Bukittinggi - Jambu Air","Bukittinggi - Manggis Ganting","Painan - Pagaruyung","Payakumbuh - Simpang Benteng","Solok - Pandan","Padang - Gajah Mada","Padang - S. Parman","Padang - Sutomo","Padang - Tarandam","Padang - Ujung Gurun"];
const DRAFT_KEY = "mt-coach-weekly-planning-draft-v3";
const DEFAULT_DATE = "2026-08-31";
function formatDate(date: string) { return new Intl.DateTimeFormat("id-ID", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${date}T00:00:00`)); }

export default function PlanningPage() {
  const [date, setDate] = useState(DEFAULT_DATE); const [branch, setBranch] = useState(BRANCHES[0]);
  const [sessions, setSessions] = useState<Session[]>([]); const [status, setStatus] = useState<"Draft" | "Finalized">("Draft");
  const [mt, setMt] = useState(masterData.mt[0] || ""); const [rombel, setRombel] = useState(masterData.rombel[0] || "");
  const [mapel, setMapel] = useState(masterData.mapel[0] || ""); const [type, setType] = useState("KBM");
  const [auviTv, setAuviTv] = useState(false); const [ld, setLd] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { try { const saved = localStorage.getItem(DRAFT_KEY); if (saved) { const parsed = JSON.parse(saved) as { sessions?: Session[]; status?: "Draft" | "Finalized" }; if (Array.isArray(parsed.sessions)) setSessions(parsed.sessions); if (parsed.status === "Finalized") setStatus("Finalized"); } } catch {} }, []);
  const selectedDateLabel = formatDate(date);
  const visibleSessions = useMemo(() => sessions.filter((s) => s.date === date && (s as Session & { branch?: string }).branch === branch), [sessions, date, branch]);
  const branchSessions = useMemo(() => sessions.filter((s) => (s as Session & { branch?: string }).branch === branch), [sessions, branch]);
  const totalRombels = new Set(branchSessions.map((s) => s.rombel)).size; const auviRombels = new Set(branchSessions.filter((s) => s.auviTv).map((s) => s.rombel)).size;
  const auviCoverage = totalRombels ? Math.round((auviRombels / totalRombels) * 100) : 0; const ldCount = branchSessions.filter((s) => s.ld).length;
  function addSession(e: FormEvent) { e.preventDefault(); if (status === "Finalized" || !mt || !rombel || !mapel || !date) return; const next = { id: Date.now(), date, time: "", mt, rombel, mapel, type, status: "Planned" as const, auviTv, ld, branch } as Session & { branch: string; mapel: string }; setSessions((prev) => [...prev, next]); setAuviTv(false); setLd(false); setMessage(""); }
  function deleteSession(id: number) { if (status !== "Finalized") setSessions((prev) => prev.filter((s) => s.id !== id)); }
  function saveDraft() { localStorage.setItem(DRAFT_KEY, JSON.stringify({ sessions, status: "Draft", savedAt: new Date().toISOString() })); setStatus("Draft"); setMessage("Draft berhasil disimpan."); }
  function finalize() { localStorage.setItem(DRAFT_KEY, JSON.stringify({ sessions, status: "Finalized", savedAt: new Date().toISOString() })); setStatus("Finalized"); setMessage("Weekly Planning berhasil difinalisasi."); }
  return <div className="page-wrap">
    <section className="planning-hero"><div className="planning-hero-row"><div><div className="eyebrow">MT COACH · OPERATIONS</div><h1>Weekly Planning</h1><p>Susun seluruh sesi secara manual, simpan sebagai Draft, lalu finalisasi saat sudah siap.</p></div><span className="badge planning-status">{status === "Draft" ? "📝 Draft" : "🔒 Finalized"}</span></div></section>
    <section className="planning-control-card"><div className="control-box"><span className="control-label">Cabang</span><select className="branch-select" value={branch} onChange={(e) => setBranch(e.target.value)} disabled={status === "Finalized"}>{BRANCHES.map((item) => <option key={item}>{item}</option>)}</select></div><div className="control-box"><span className="control-label">Tanggal Planning</span><div className="date-control"><div className="date-icon">📅</div><input className="date-input" type="date" value={date} onChange={(e) => setDate(e.target.value)} disabled={status === "Finalized"} /></div><div className="date-caption">{selectedDateLabel}</div></div></section>
    <div className="grid planning-kpis"><div className="card planning-kpi"><div className="planning-kpi-top"><div className="kpi-label">Total Session</div><div className="kpi-mini-icon">📋</div></div><div className="kpi-value">{branchSessions.length}</div><div className="kpi-note">Semua sesi input manual</div></div><div className="card planning-kpi"><div className="planning-kpi-top"><div className="kpi-label">AuVi TV Coverage</div><div className="kpi-mini-icon">🎥</div></div><div className="kpi-value">{auviCoverage}%</div><div className="kpi-note">{auviRombels}/{totalRombels} rombel · target ≥ 50%</div></div><div className="card planning-kpi"><div className="planning-kpi-top"><div className="kpi-label">LD</div><div className="kpi-mini-icon">👥</div></div><div className="kpi-value">{ldCount}<span style={{ fontSize: 14, color: "#94a3b8", marginLeft: 5 }}>/ 10</span></div><div className="kpi-note">Target 10 sesi per minggu</div></div></div>
    <form className="card input-card" onSubmit={addSession}><div className="section-title"><div><h2>Tambah Sesi</h2><p>Input sesi untuk <strong>{selectedDateLabel}</strong>. Jam tidak diperlukan.</p></div><span className="section-chip">MASTER DATA</span></div><div className="planning-form-grid"><label className="planning-field"><span>MT</span><select value={mt} onChange={(e) => setMt(e.target.value)} disabled={status === "Finalized"} required>{masterData.mt.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="planning-field"><span>Rombel</span><select value={rombel} onChange={(e) => setRombel(e.target.value)} disabled={status === "Finalized"} required>{masterData.rombel.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="planning-field"><span>Mapel</span><select value={mapel} onChange={(e) => setMapel(e.target.value)} disabled={status === "Finalized"} required>{masterData.mapel.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="planning-field"><span>Jenis Sesi</span><select value={type} onChange={(e) => setType(e.target.value)} disabled={status === "Finalized"}><option>KBM</option><option>AuVi TV</option><option>LD</option><option>Other</option></select></label></div><div className="planning-options"><label className="option-pill"><input type="checkbox" checked={auviTv} onChange={(e) => setAuviTv(e.target.checked)} disabled={status === "Finalized"} /> 🎥 AuVi TV</label><label className="option-pill"><input type="checkbox" checked={ld} onChange={(e) => setLd(e.target.checked)} disabled={status === "Finalized"} /> 👥 LD</label></div><button className="add-session-btn" type="submit" disabled={status === "Finalized"}>＋ Tambah Sesi</button></form>
    <section className="card planning-table-card"><div className="planning-table-head"><div><h2>Daftar Sesi</h2><p>{branch} · {selectedDateLabel}</p></div><span className="section-chip">{visibleSessions.length} sesi</span></div><div className="planning-table-wrap"><table><thead><tr><th>MT</th><th>Rombel</th><th>Mapel</th><th>Jenis</th><th>AuVi TV</th><th>LD</th><th>Aksi</th></tr></thead><tbody>{visibleSessions.length === 0 ? <tr><td colSpan={7}><div className="empty-state"><div className="empty-icon">📋</div><strong>Belum ada sesi</strong><p>Tambahkan sesi pertama untuk tanggal ini melalui form di atas.</p></div></td></tr> : visibleSessions.map((session) => <tr key={session.id}><td><span className="table-primary">{session.mt}</span></td><td>{session.rombel}</td><td><span className="table-primary">{(session as Session & { mapel?: string }).mapel || "—"}</span></td><td>{session.type}</td><td><span className={`badge ${session.auviTv ? "green" : "blue"}`}>{session.auviTv ? "✓ Assigned" : "— Belum"}</span></td><td><span className={`badge ${session.ld ? "green" : "blue"}`}>{session.ld ? "✓ Assigned" : "— Belum"}</span></td><td><button className="row-delete" type="button" onClick={() => deleteSession(session.id)} disabled={status === "Finalized"}>Hapus</button></td></tr>)}</tbody></table></div></section>
    <div className="finalize-bar"><div><strong>{branch}</strong><small>{message || "Input sesi selesai? Simpan dulu sebagai Draft."}</small></div><div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}><button type="button" className="secondary-btn" onClick={saveDraft} disabled={status === "Finalized"}>📝 Simpan sebagai Draft</button><button type="button" className="primary-btn" onClick={finalize} disabled={status === "Finalized" || sessions.length === 0}>🔒 Finalize Planning</button></div></div>
  </div>;
}
